apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vol_roldbdg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volume_role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sonia
