apiVersion: v1
kind: Service
metadata:
  name: middleware
spec:
  selector:
    app: middleware
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30007
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: cbagade/pymiddleware:v8
        ports:
          # container port (app will be exposed at 5000)
          - containerPort: 5000
        env:
        - name: MONGO_ADDRESS
          value: "mongodb.kube-learnings" # mongo db service + . + namespace
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongouser
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-init-creds
              key: mongopassword
  selector:
    matchLabels:
      app: middleware



# docker build -t cbagade/pymiddleware:v8 .
# docker push cbagade/pymiddleware:v8
# kubectl apply -f mongo_deployment.yaml -f app_deployment.yaml
# though we have multiple mongo pods, but they all share same PV
# data is write to and read from same volume
# kubectl get pods -w  (wait for pods to be in running state)
# there are multiple mongo pods and reading/writing to same PV

# following will fetch nothing (or something from previous exercise)
# curl 'http://localhost:30007/api/v1/fruits'

# post data 

#  curl --location 'http://localhost:30007/api/v1/fruits' \
#   --header 'Content-Type: application/json' \
#  --data '{"fruitName":"Apple","from":"Tamilnadu","nutrients":"Vitamin B, Vitamin K","price":"200.50","organic":true,"description":"An avocado is a bright green fruit with a large pit and dark leathery skin. They'\''re also known as alligator pears or butter fruit. Avocados are a favorite of the produce section. They'\''re the go-to ingredient for guacamole dips."}'

# verify
# curl 'http://localhost:30007/api/v1/fruits'

# kubectl delete -f mongo_deployment.yaml -f app_deployment.yaml
# ensure all pod, svc, pvc and pv are deleted
