apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: svc-demo
    # how this pod should look like
    spec:
      containers:
      - name: second-app-container
        image: cbagade/pykubd-first-app:v5
        ports:
          - containerPort: 5000
  selector:
    matchLabels:
      app: svc-demo


