apiVersion: apps/v1
kind: Deployment
metadata:
  name: withoutvol-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: withoutvol-app
    spec:
      containers:
      - name: withoutvol-app-container
        image: cbagade/pykube-data-icwithoutvol:v25
        ports:
          - containerPort: 5000        
  selector:
    matchLabels:
      app: withoutvol-app



# docker build -t cbagade/pykube-data-icwithoutvol:v25 .
# docker push cbagade/pykube-data-icwithoutvol:v25
# kubectl apply -f app_deployment.yaml -f service.yaml
# ensure pods in running state
# kubectl get pods -w

# curl 'http://localhost:30008/api/v1/fruits'

# post data (existing fruits plus appending additional fruits)
# curl --location 'http://localhost:30008/api/v1/fruits' \
#  --header 'Content-Type: application/json' \
# --data '{"fruitName":"Apple","from":"Tamilnadu","nutrients":"Vitamin B, Vitamin K","price":"200.50","organic":true,"description":"An avocado is a bright green fruit with a large pit and dark leathery skin. They'\''re also known as alligator pears or butter fruit. Avocados are a favorite of the produce section. They'\''re the go-to ingredient for guacamole dips."}'


# Verify the changes
# curl 'http://localhost:30008/api/v1/fruits'

# GET  app_2/api/v1/fruits/error change port to 30008, this will restart container
# curl 'http://localhost:30008/api/v1/fruits/error'

# This action will put container in error state and restart (pod is not restarted)
# kubectl get pods -w
# GET fruits
# curl 'http://localhost:30008/api/v1/fruits'
# changes are lost, when container restart
# obviously if you delete and recreate pod, changes won't be there
# also pod restart won't have changes
# kubectl delete -f app_deployment.yaml -f service.yaml