apiVersion: v1
kind: Service
metadata:
  name: withoutvol-svc
spec:
  selector:
    app: withoutvol-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30008
  type: NodePort
