apiVersion: batch/v1
kind: Job
metadata:
  name: task-job
spec:
  template:
    spec:
      containers:
      - name: task-app
        image: cbagade/task-app:v1
        command: ["python3", "app.py"]
      restartPolicy: Never

    
    # kubectl apply -f job.yaml
    # kubectl get jobs
    # kubectl logs <pod_name>
    # kubectl delete -f job.yaml
    