apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod_roldbdg
  namespace: kube-learnings
subjects:
- kind: User
  name: sonia
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-role
  apiGroup: rbac.authorization.k8s.io