apiVersion: v1
kind: LimitRange
metadata:
  name: default-values-cpu
  namespace: kube-learnings
spec:
  limits:
  - default:   # default limits if not specified
      cpu: 750m
      memory: 1Gi
    defaultRequest: # default requests  if not specified
      cpu: 500m
      memory: 500Mi
    max: # if max is specified, then limit must be specified across all containers on the pod
      cpu: "2"
      memory: 2Gi
    min: # if min is specified, then request must be specified across all containers on the pod
      cpu: 100m
      memory: 500Mi
    type: Container

  # These are default values for container resources , if not specified on pod
  # These are set at namespace level