# refer https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# will list all details of enclosing specs

apiVersion: v1
kind: Pod
metadata:
  name: res-reqt
spec:
  containers:
  - name: res-reqt-container
    image: cbagade/pykubd-first-app:v5
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
    # resource requirement for container
    resources:
      requests:
        memory: "256Mi"
        # 1 count means total CPU processing power for one pod
        # 0.5 will reserve half a CPU processing power for one pod
        # .1m means 100 millicore of total CPU processing power for one pod
        cpu: 0.5
      limits:
        memory: "512Mi"
        cpu: 2

# kubectl apply -f pod.yaml
# kubectl get pods -w
# to see resource consumption
# kubectl top pods
# kubectl delete -f pod.yaml
